### ISSUE TITLE
does GetAllEntitiesAsync work?

### ISSUE THREAD

**Issue by gbertoncelli** [andreluizsecco/Cognitive-LUIS-Programmatic#9] opened 2018-05-15 07:50 UTC
I'm trying to use GetAllEntitiesAsync (luisId, luisVersion) but it does not work in my case:
 IReadOnlyCollection<Entity> entities = await luisClient.GetAllEntitiesAsync(_config.LuisId, _config.LuisVersion);
returns always a collection with 0 items... Why is that? I've checked and for instance with GetAllIntentsAsync the _config.LuisId and _config.LuisVersion work.

**Comment by andreluizsecco** [comment] 2018-05-17 15:56
Are you sure you have entities added to your LUIS app?

**Comment by gbertoncelli** [comment] 2018-05-17 16:59
Pretty sure... But for example in the LuIs web portal I cannot find out the IDs of the entity (is that normal?).. In the project I needed the names of the entities but I've solved the situation saving the names in a database.

**Comment by andreluizsecco** [comment] 2018-05-19 14:03
Could you post a print from your LUIS portal entities screen?

**Comment by andreluizsecco** [comment] 2018-06-18 23:51
Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

**Closed as completed by andreluizsecco** 2018-06-18 23:51 UTC
Labels: question, insufficient-info
